[env]
TERM = "xterm-256color"

[window]
padding = { x = 0, y = 0 }

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrains Mono Nerd Font", style = "Bold Italic" }
size = 12.00
glyph_offset = { x = 1, y = 0 }
offset = { x = 0, y = 1 }
